dist: focal
sudo: required

language: php

php:
    - '7.4'
    - '8.0'

install:
    - 'composer install --prefer-dist --no-suggest'

before_script:
    - |
        # Enable APCu
        yes '' | pecl install -f apcu
        echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
    - 'cd test && ../vendor/bin/phpunit -c phpunit.xml --debug'

cache:
  directories:
    - '$HOME/.composer/cache'
